Punish_Reward/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

import views

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path('', views.show_base_page, name='login'),
    path(r'master/', include('master.urls', namespace='master')),
    path(r'employee/', include('employee.urls', namespace='employee')),
    path(r'evaluator/', include('evaluator.urls', namespace='evaluator')),
    path(r'manager/', include('manager.urls', namespace='manager')),
    path(r'logout/', views.logout, name='logout')
]

employee/urls.py
from django.conf.urls import url

from . import views

app_name = 'employee'
urlpatterns = [
    url(r'^review_request', views.review_request, name='review_request'),
    url(r'^view_evaluations', views.view_evaluations, name='view_evaluations'),
    url(r'^enter_var_values', views.enter_var_values, name='enter_var_values'),
    url(r'^', views.show_employee_page, name='employee_first_page'),
]

evaluator/urls.py
from django.conf.urls import url

from . import views

app_name = 'evaluator'
urlpatterns = [
    url(r'^view_employees', views.view_employees, name='view_employees'),
    url(r'^enter_var_values', views.enter_var_values, name='enter_var_values'),
    url(r'^check_re-evaluation_request', views.check_reevaluation_request, name='check_re-evaluation_request'),
    url(r'^evaluation', views.evaluation, name='evaluation'),
    url(r'^', views.show_employee_page, name='employee_first_page'),
]

manager/urls.py
from django.conf.urls import url

from . import views

app_name = 'manager'
urlpatterns = [
url(r'^check_review_request', views.check_review_request, name='check_review_request'),
    url(r'^view_review_requests', views.view_review_requests, name='view_review_requests'),
    url(r'^view_employees', views.view_employees, name='view_employees'),
    url(r'^choose_evaluation_way', views.choose_evaluation_way, name='choose_evaluation_way'),
    url(r'^criterion_page', views.show_criterion_page, name='criterion_page'),
    url(r'^add_criterion', views.add_criterion, name='add_criterion'),
    url(r'^add_employees', views.add_employees_page, name='add_employees'),
    url(r'^criterion_page', views.show_criterion_page, name='criterion_page'),
    url(r'^add_criterion', views.add_criterion, name='add_criterion'),

    url(r'^edit_punish', views.edit_punish_page, name='edit_punish'),
    url(r'^add_punish', views.add_punish_page, name='add_punish'),
    url(r'^punish_page', views.show_punish_page, name='punish_page'),
    url(r'^employees_page', views.show_employees_page, name='employees_page'),
    url(r'^', views.show_manager_page, name='manager_first_page'),
]

master/urls.py
from django.conf.urls import url

from . import views

app_name = 'master'
urlpatterns = [
    url(r'^add_employee', views.add_employee, name='add_employee'),

    url(r'^view_evaluator', views.view_evaluator, name='view_evaluator'),
    url(r'^view_re-evaluation_request', views.view_reevaluation_request, name='view_re-evaluation_request'),
    url(r'^choose_final_evaluation', views.choose_final_evaluation,name='choose_final_evaluation'),
    url(r'^view_employees', views.view_employees, name='view_employees'),
    url(r'^add_evaluator', views.add_evaluator, name='add_evaluator'),
    url(r'^choose_punish_reward', views.choose_punish_reward, name='choose_punish_reward'),
    url(r'^view_criteria', views.view_criteria, name='view_criteria'),
    url(r'^edit_master', views.edit_master_page, name='edit_master'),
    url(r'^add_criterion', views.add_criterion_page, name='add_criterion'),
    url(r'^each_request', views.show_each_request, name='each_request'),
    url(r'^request_page', views.show_request_page, name='request_page'),
    url(r'^criterion_page', views.show_criterion_page, name='criterion_page'),
    url(r'^', views.show_master_page, name='master_first_page'),
]

employee/models.py
# Create your models here.

evaluator/models.py
from django.db import models

# Create your models here.

manager/models.py
# Create your models here.

master/models.py
# Create your models here.

employee/views.py
from django.shortcuts import render


# Create your views here.


def enter_var_values(request):
    return render(request, 'employee/enter_var_values.html')
def view_evaluations(request):
    return render(request, 'employee/view_evaluations.html')


def review_request(request):
    return render(request, 'employee/review_request.html')
def evaluation(request):
    return render(request, 'evaluator/evaluation.html')
def show_employee_page(request):
    return render(request, 'employee/employee.html')

evaluator/views.py
from django.shortcuts import render


# Create your views here.


def enter_var_values(request):
    return render(request, 'evaluator/enter_var_values.html')
def view_employees(request):
    return render(request, 'evaluator/view_employees.html')
def check_reevaluation_request(request):
    return render(request, 'evaluator/check_re-evaluation_request.html')
def evaluation(request):
    return render(request, 'evaluator/evaluation.html')
def show_employee_page(request):
    return render(request, 'evaluator/evaluator.html')

manager/views.py
from django.shortcuts import render


# Create your views here.
def view_review_requests(request):
    return render(request, 'manager/view_review_requests.html')


def check_review_request(request):
    return render(request, 'manager/check_review_request.html')


def view_employees(request):
    return render(request, 'manager/view_employees.html')


def choose_evaluation_way(request):
    return render(request, 'manager/choose_evaluation_way.html')


def show_manager_page(request):
    return render(request, 'manager/manager.html')


def show_punish_page(request):
    return render(request, 'manager/punish.html')


def add_punish_page(request):
    return render(request, 'manager/add_punish.html')


def add_employees_page(request):
    return render(request, 'manager/add_employees.html')

def add_criterion(request):
    return render(request, 'manager/add_criterion.html')

def show_employees_page(request):
    return render(request, 'manager/show_employees.html')

def show_criterion_page(request):
    return render(request, 'manager/criterion.html')


def edit_punish_page(reqeust):
    return render(reqeust, 'manager/edit_punish.html')

master/views.py
from django.shortcuts import render


# Create your views here.

def add_employee(request):
    return render(request, 'master/add_employee.html')
def view_evaluator(request):
    return render(request, 'master/view_evaluator.html')
def view_reevaluation_request(request):
    return render(request, 'master/view_re-evaluation_request.html')
def choose_final_evaluation(request):
    return render(request, 'master/choose_final_evaluation.html')
def view_employees(request):
    return render(request, 'master/view_employees.html')

def add_evaluator(request):
    return render(request, 'master/add_evaluator.html')

def choose_punish_reward(request):
    return render(request, 'master/choose_punish_reward.html')
def view_criteria(request):
    return render(request, 'master/view_criteria.html')

def show_master_page(request):
    return render(request, 'master/master.html')


def show_criterion_page(request):
    return render(request, 'master/criterion.html')


def add_criterion_page(request):
    return render(request, 'master/add_criterion.html')


def edit_master_page(request):
    return render(request, 'master/edit_master.html')


def show_each_request(request):
    return render(request, 'master/each_request_page.html')


def show_request_page(request):
    return render(request, 'master/review_request_page.html')

views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render


def show_base_page(request):
    return render(request, 'login.html')


def show_manager_page(request):
    return render(request, 'manager/manager.html')


def logout(request):
    return HttpResponseRedirect('/')

templates/employee/employee.html
{% extends 'main.html' %}

{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>

{% endblock special_static %}


{% block menu %}
    <li>
        <a href="#">واحد</a>
          <ul class="noJS">
            <li><a href="{% url 'employee:enter_var_values' %}">مقداردهی</a></li>
            <li><a href="{% url 'employee:view_evaluations' %}">مشاهده ارزیابی‌ها</a></li>
          </ul>
    </li>
    <li><a href="/logout/">خروج</a></li>
{% endblock menu %}

templates/evaluator/check_re-evaluation_request.html
{% extends 'evaluator/evaluator.html' %}


{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/form.css" %}"/>
{% endblock special_static %}


{% block content %}
    <h2 class="page_title">بررسی درخواست ارزیابی مجدد مهدیه بهروزی فر</h2>
    <div class="col-md-8 center_view">
        <div class="form-area">
            <form role="form">
                <br style="clear:both">



                <div class="form-group">
                    <label for="input_number">کد پرسنلی</label>
                    <input disabled type="number" class="form-control" id="input_number" placeholder="93105512" name="input_number"/>
                </div>

                <div class="form-group">
                    <label for="input_number">نام و نام خانوادگی</label>
                    <input disabled type="number" class="form-control" id="input_number" placeholder="مهدیه بهروزی فر" name="input_number"/>
                </div>
                <div class="form-group">
                    <label for="input_number">عنوان</label>
                    <input disabled type="number" class="form-control" id="input_number" name="input_number" placeholder="اشتباه در محاسبه"/>
                </div>
                <div class="form-group">
                    <label for="input_number">توضیحات</label>
                    <input disabled type="number" class="form-control" id="input_number" placeholder="در محاسبه فرمول مشکلی رخ داده است" name="input_number"/>
                </div>
                <div class="form-group">
                    <label for="formula">نام معیار</label>
                    <input type="text" disabled class="form-control" id="formula" placeholder="حقوق" name="formula"/>
                </div>

                <div class="form-group">
                    <label for="var1">ارزیاب دیگر</label>
                    <input type="text" disabled class="form-control" id="formula" placeholder="صابره فائز" name="formula"/>

                </div>
                <div class="form-group">
                    <label for="var1">نتیجه ارزیاب دیگر</label>
                    <input type="number" disabled class="form-control" id="formula" placeholder="7" name="formula"/>

                </div>

                <button type="button" id="submit" name="submit" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'evaluator:evaluation' %}'" >ارزیابی</button>
                <a href="{% url 'master:criterion_page' %}" type="button" class="btn btn-default btn-lg">بازگشت</a>
            </form>
        </div>
    </div>
{% endblock content %}

templates/evaluator/evaluator.html
{% extends 'main.html' %}

{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>

{% endblock special_static %}


{% block menu %}
    <li>
        <a href="#">واحد</a>
          <ul class="noJS">
            <li><a href="{% url 'evaluator:view_employees' %}">مشاهده ارزیابی شوندگان</a></li>
            <li><a href="{% url 'evaluator:enter_var_values' %}">وارد کردن مقادیر متغییرها</a></li>
            <li><a href="{% url 'evaluator:check_re-evaluation_request' %}">بررسی درخواست ارزیابی مجدد</a></li>
            <li><a href="{% url 'evaluator:evaluation' %}">ارزیابی</a></li>
          </ul>
    </li>
    <li>
        <a href="#">معیار</a>
          <ul class="noJS">
            <li><a href="{% url 'master:view_criteria' %}">مشاهده معیارها</a></li>

          </ul>
    </li>
    <li><a href="/logout/">خروج</a></li>
{% endblock menu %}

templates/evaluator/view_employees.html
{% extends 'evaluator/evaluator.html' %}





{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/table.css" %}"/>
{#    <link rel="stylesheet" type="text/css" href="{% static "css/table_5_columns.css" %}"/>#}
    <script>
    $(function() {
        $("tr").click(function(e) { // limit click to children of mainmenue
            $("#actions").removeClass('hide').addClass('show');
            var name = $(this).find('td').get(2).innerHTML;
            console.log(name);
            $('.overlay').css("opacity", "0.5");
            document.getElementById('criterion').innerHTML = name;
            e.stopPropagation();
        });
        $(document).on('click','*',function(e){
            e.stopPropagation();

            $("#actions").removeClass('show').addClass('hide');
            $('.overlay').css("opacity", "1");
        });


    });
    </script>
{% endblock special_static %}


{% block content %}
    <h2 class="page_title">لیست کارمندان</h2>
    <div class="cont">
        <table class="overlay">
        <tr>
            <th>ردیف</th>
            <th>واحد</th>
            <th>کدپرسنلی</th>
            <th>نام</th>
            <th>نام خانوادگی</th>
        </tr>
            <tr>
                <td>1</td>
                <td>1</td>
                <td>93105512</td>
                <td>مهدیه</td>
                <td>بهروزی فر</td>
            </tr>
            <tr>
                <td>2</td>
                <td>1</td>
                <td>93111558</td>
                <td>صابره</td>
                <td>فائز</td>
            </tr>
            <tr>
                <td>3</td>
                <td>1</td>
                <td>93105494</td>
                <td>حانیه</td>
                <td>برغی</td>
            </tr>

    </table>
<div id="actions" class="hide">
    <li id="criterion">
    </li>
    <li class="action"><a href="{% url 'evaluator:evaluation' %}">ارزیابی</a></li>
    <li class="action"><a href="{% url 'evaluator:enter_var_values' %}">مقداردهی</a></li>

</div>
    </div>

{% endblock content %}

templates/evaluator/view_re-evaluation_requests.html
{% extends 'evaluator/evaluator.html' %}





{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/table.css" %}"/>
{#    <link rel="stylesheet" type="text/css" href="{% static "css/table_5_columns.css" %}"/>#}
    <script>
    $(function() {
        $("tr").click(function(e) { // limit click to children of mainmenue
            $("#actions").removeClass('hide').addClass('show');
            var name = $(this).find('td').get(1).innerHTML;
            console.log(name);
            $('.overlay').css("opacity", "0.5");
            document.getElementById('criterion').innerHTML = name;
            e.stopPropagation();
        });
        $(document).on('click','*',function(e){
            e.stopPropagation();

            $("#actions").removeClass('show').addClass('hide');
            $('.overlay').css("opacity", "1");
        });


    });
    </script>
{% endblock special_static %}


{% block content %}
    <h2 class="page_title">لیست درخواست‌های ارزیابی مجدد</h2>
    <div class="cont">
        <table class="overlay">
        <tr>
            <th>ردیف</th>
            <th>واحد</th>
            <th>کدپرسنلی</th>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th>عنوان درخواست</th>

            <th>تصمیم‌گیری نهایی</th>
        </tr>
            <tr>
                <td>1</td>
                <td>1</td>
                <td>93105512</td>
                <td>مهدیه</td>
                <td>بهروزی فر</td>
                <td>اشتباه در محاسبه</td>
                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'master:choose_final_evaluation' %}'">تصمیم‌گیری نهایی</button></td>
            </tr>
            <tr>
                <td>2</td>
                <td>1</td>
                <td>93111558</td>
                <td>صابره</td>
                <td>فائز</td>
                <td>اشتباه در محاسبه</td>
                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'master:choose_final_evaluation' %}'">تصمیم‌گیری نهایی</button></td>

            </tr>
            <tr>
                <td>3</td>
                <td>1</td>
                <td>93105494</td>
                <td>حانیه</td>
                <td>برغی</td>
                <td>اشتباه در محاسبه</td>

                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'master:choose_final_evaluation' %}'">تصمیم‌گیری نهایی</button></td>
            </tr>

    </table>
<div id="actions" class="hide">
    <li id="criterion">
    </li>
    <li class="action"><a href="{% url 'master:choose_evaluation_way' %}">تعیین روش ارزیابی</a></li>
    <li class="action">
    ویرایش روش ارزیابی
    </li>
    <li class="action">
    تعیین روش پاداش و تنبیه
    </li>
    <li class="action">
    ویرایش روش پاداش و تنبیه
    </li>
</div>
    </div>

{% endblock content %}

templates/manager/manager.html
{% extends 'main.html' %}

{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>

{% endblock special_static %}


{% block menu %}
    <li>
        <a href="#">واحد</a>
          <ul class="noJS">
            <li><a href="{% url 'manager:view_employees' %}">مشاهده کارمندان واحد</a></li>
            <li><a href="{% url 'manager:view_review_requests' %}">بررسی درخواست بازنگری</a></li>
          </ul>
    </li>
    <li>
        <a href="#">معیار</a>
          <ul class="noJS">
            <li><a href="{% url 'manager:add_criterion' %}">افزودن معیار</a></li>
              <li><a href="{% url 'manager:criterion_page' %}">تعیین روش ارزیابی معیار</a></li>

          </ul>
    </li>
    <li><a href="/logout/">خروج</a></li>
{% endblock menu %}

templates/manager/view_re-evaluation_request.html
{% extends 'manager/manager.html' %}





{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/table.css" %}"/>
{#    <link rel="stylesheet" type="text/css" href="{% static "css/table_5_columns.css" %}"/>#}
    <script>
    $(function() {
        $("tr").click(function(e) { // limit click to children of mainmenue
            $("#actions").removeClass('hide').addClass('show');
            var name = $(this).find('td').get(1).innerHTML;
            console.log(name);
            $('.overlay').css("opacity", "0.5");
            document.getElementById('criterion').innerHTML = name;
            e.stopPropagation();
        });
        $(document).on('click','*',function(e){
            e.stopPropagation();

            $("#actions").removeClass('show').addClass('hide');
            $('.overlay').css("opacity", "1");
        });


    });
    </script>
{% endblock special_static %}


{% block content %}
    <h2 class="page_title">لیست درخواست‌های ارزیابی مجدد</h2>
    <div class="cont">
        <table class="overlay">
        <tr>
            <th>ردیف</th>
            <th>واحد</th>
            <th>کدپرسنلی</th>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th>عنوان درخواست</th>

            <th>تصمیم‌گیری نهایی</th>
        </tr>
            <tr>
                <td>1</td>
                <td>1</td>
                <td>93105512</td>
                <td>مهدیه</td>
                <td>بهروزی فر</td>
                <td>اشتباه در محاسبه</td>
                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'manager:choose_final_evaluation' %}'">تصمیم‌گیری نهایی</button></td>
            </tr>
            <tr>
                <td>2</td>
                <td>1</td>
                <td>93111558</td>
                <td>صابره</td>
                <td>فائز</td>
                <td>اشتباه در محاسبه</td>
                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'manager:choose_final_evaluation' %}'">تصمیم‌گیری نهایی</button></td>

            </tr>
            <tr>
                <td>3</td>
                <td>1</td>
                <td>93105494</td>
                <td>حانیه</td>
                <td>برغی</td>
                <td>اشتباه در محاسبه</td>

                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'manager:choose_final_evaluation' %}'">تصمیم‌گیری نهایی</button></td>
            </tr>

    </table>
<div id="actions" class="hide">
    <li id="criterion">
    </li>
    <li class="action"><a href="{% url 'master:choose_evaluation_way' %}">تعیین روش ارزیابی</a></li>
    <li class="action">
    ویرایش روش ارزیابی
    </li>
    <li class="action">
    تعیین روش پاداش و تنبیه
    </li>
    <li class="action">
    ویرایش روش پاداش و تنبیه
    </li>
</div>
    </div>

{% endblock content %}

templates/manager/view_review_requests.html
{% extends 'manager/manager.html' %}





{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/table.css" %}"/>
{#    <link rel="stylesheet" type="text/css" href="{% static "css/table_5_columns.css" %}"/>#}
    <script>
    $(function() {
        $("tr").click(function(e) { // limit click to children of mainmenue
            $("#actions").removeClass('hide').addClass('show');
            var name = $(this).find('td').get(1).innerHTML;
            console.log(name);
            $('.overlay').css("opacity", "0.5");
            document.getElementById('criterion').innerHTML = name;
            e.stopPropagation();
        });
        $(document).on('click','*',function(e){
            e.stopPropagation();

            $("#actions").removeClass('show').addClass('hide');
            $('.overlay').css("opacity", "1");
        });


    });
    </script>
{% endblock special_static %}


{% block content %}
    <h2 class="page_title">لیست درخواست‌های بازنگری</h2>
    <div class="cont">
        <table class="overlay">
        <tr>
            <th>ردیف</th>
            <th>کدپرسنلی</th>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th>عنوان درخواست</th>
            <th>بررسی</th>
        </tr>
            <tr>
                <td>1</td>
                <td>93105512</td>
                <td>مهدیه</td>
                <td>بهروزی فر</td>
                <td>اشتباه در محاسبه</td>
                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'manager:check_review_request' %}'">بررسی</button></td>
            </tr>
            <tr>
                <td>2</td>
                <td>93111558</td>
                <td>صابره</td>
                <td>فائز</td>
                <td>اشتباه در محاسبه</td>
                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'manager:check_review_request' %}'">بررسی</button></td>

            </tr>
            <tr>
                <td>3</td>
                <td>93105494</td>
                <td>حانیه</td>
                <td>برغی</td>
                <td>اشتباه در محاسبه</td>
                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'manager:check_review_request' %}'">بررسی</button></td>
            </tr>

    </table>
<div id="actions" class="hide">
    <li id="criterion">
    </li>
    <li class="action"><a href="{% url 'manager:choose_evaluation_way' %}">تعیین روش ارزیابی</a></li>
    <li class="action">
    ویرایش روش ارزیابی
    </li>
    <li class="action">
    تعیین روش پاداش و تنبیه
    </li>
    <li class="action">
    ویرایش روش پاداش و تنبیه
    </li>
</div>
    </div>

{% endblock content %}

templates/master/master.html
{% extends 'main.html' %}

{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>

{% endblock special_static %}


{% block menu %}
    <li>
        <a href="#">واحد</a>
          <ul class="noJS">
            <li><a href="{% url 'master:view_employees' %}">مشاهده کارمندان</a></li>
              <li><a href="{% url 'master:view_evaluator' %}">مشاهده ارزیابی کنندگان</a></li>

            <li><a href="{% url 'master:add_evaluator' %}">افزودن ارزیابی کننده</a></li>
               <li><a href="{% url 'master:add_employee' %}">افزودن کارمند</a></li>
              <li><a href="{% url 'master:view_re-evaluation_request' %}">مشاهده درخواست های ارزیابی مجدد</a></li>
          </ul>
    </li>
    <li>
        <a href="#">معیار</a>
          <ul class="noJS">
            <li><a href="{% url 'master:view_criteria' %}">مشاهده معیارها</a></li>

          </ul>
    </li>
    <li><a href="/logout/">خروج</a></li>
{% endblock menu %}

templates/master/view_re-evaluation_request.html
{% extends 'master/master.html' %}





{% block special_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/table.css" %}"/>
{#    <link rel="stylesheet" type="text/css" href="{% static "css/table_5_columns.css" %}"/>#}
    <script>
    $(function() {
        $("tr").click(function(e) { // limit click to children of mainmenue
            $("#actions").removeClass('hide').addClass('show');
            var name = $(this).find('td').get(1).innerHTML;
            console.log(name);
            $('.overlay').css("opacity", "0.5");
            document.getElementById('criterion').innerHTML = name;
            e.stopPropagation();
        });
        $(document).on('click','*',function(e){
            e.stopPropagation();

            $("#actions").removeClass('show').addClass('hide');
            $('.overlay').css("opacity", "1");
        });


    });
    </script>
{% endblock special_static %}


{% block content %}
    <h2 class="page_title">لیست درخواست‌های ارزیابی مجدد</h2>
    <div class="cont">
        <table class="overlay">
        <tr>
            <th>ردیف</th>
            <th>واحد</th>
            <th>کدپرسنلی</th>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th>عنوان درخواست</th>

            <th>تصمیم‌گیری نهایی</th>
        </tr>
            <tr>
                <td>1</td>
                <td>1</td>
                <td>93105512</td>
                <td>مهدیه</td>
                <td>بهروزی فر</td>
                <td>اشتباه در محاسبه</td>
                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'master:choose_final_evaluation' %}'">تصمیم‌گیری نهایی</button></td>
            </tr>
            <tr>
                <td>2</td>
                <td>1</td>
                <td>93111558</td>
                <td>صابره</td>
                <td>فائز</td>
                <td>اشتباه در محاسبه</td>
                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'master:choose_final_evaluation' %}'">تصمیم‌گیری نهایی</button></td>

            </tr>
            <tr>
                <td>3</td>
                <td>1</td>
                <td>93105494</td>
                <td>حانیه</td>
                <td>برغی</td>
                <td>اشتباه در محاسبه</td>

                <td><button type="button" id="check" style="float: none" name="check" class="btn btn-default btn-lg" onclick="window.location.href='{% url 'master:choose_final_evaluation' %}'">تصمیم‌گیری نهایی</button></td>
            </tr>

    </table>
<div id="actions" class="hide">
    <li id="criterion">
    </li>
    <li class="action"><a href="{% url 'manager:choose_evaluation_way' %}">تعیین روش ارزیابی</a></li>
    <li class="action">
    ویرایش روش ارزیابی
    </li>
    <li class="action">
    تعیین روش پاداش و تنبیه
    </li>
    <li class="action">
    ویرایش روش پاداش و تنبیه
    </li>
</div>
    </div>

{% endblock content %}

templates/newtest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <script>
        $('#some-button').on('click', function () {
    $('#overlay, #overlay-back').fadeIn(500);
});

    </script>
</head>
<body>
<a id="some-button" href="#">click me</a>
<div id="overlay-back"></div>
<div id="overlay"><span>YOUR HTML GOES HERE</span></div>

</body>
</html>